/*
 * Copyright (c) 2026 Danilo Borges (https://github.com/daniloborges)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 */

import { KnowledgeRecord } from "@/types/knowledge"
import { LLM } from "@/types"
import { updateKnowledgeRecord } from "@/lib/local-db/knowledge"
import { Dispatch, SetStateAction } from "react"

const ENRICH_PROMPT = (content: string) =>
  `Give a short filename (no extension, max 5 words) and a one-sentence description for this content.\nRespond ONLY as JSON: { "title": "...", "summary": "..." }\n\nContent:\n${content}`

// Placeholder titles are generated by extract.ts for non-markdown/html content.
// Pattern: "typescript · 10:42" — if the title matches this, LLM may override it.
const PLACEHOLDER_TITLE_RE = /^.+ · \d{2}:\d{2}$/

// Local models: provider === "local" (auto-discovered via RFC-0001 discovery route)
// OR any model with an explicit baseUrl (manually configured custom models).
// Cloud models without baseUrl are not auto-enriched in v0 — RFC-0003 will add a "✦ nomear" button.
function isLocalModel(modelData: LLM): boolean {
  return modelData.provider === "local" || !!modelData.baseUrl
}

function getBaseUrl(modelData: LLM): string {
  if (modelData.baseUrl) return modelData.baseUrl
  // NEXT_PUBLIC_ env vars are inlined at build time; safe to access in renderer.
  // Falls back to the oMLX / Ollama default if not configured.
  try {
    const envUrl = process.env.NEXT_PUBLIC_OLLAMA_URL
    if (envUrl) return envUrl
  } catch {
    // process may not be available in some runtime environments
  }
  return "http://localhost:11434"
}

async function callEnrichment(
  content: string,
  modelData: LLM
): Promise<{ title: string; summary: string } | null> {
  const baseUrl = getBaseUrl(modelData)
  const headers: Record<string, string> = {
    "Content-Type": "application/json"
  }
  if (modelData.apiKey) {
    headers["Authorization"] = `Bearer ${modelData.apiKey}`
  }

  let response: Response
  try {
    response = await fetch(`${baseUrl}/v1/chat/completions`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        model: modelData.modelId,
        messages: [{ role: "user", content: ENRICH_PROMPT(content) }],
        temperature: 0.3,
        stream: false
      })
    })
  } catch {
    return null
  }

  if (!response.ok) return null

  try {
    const data = await response.json()
    const raw: string =
      data?.choices?.[0]?.message?.content ?? data?.message?.content ?? ""

    // Extract JSON from the response (model may wrap it in prose)
    const jsonMatch = raw.match(/\{[\s\S]*?\}/)
    if (!jsonMatch) return null

    const parsed = JSON.parse(jsonMatch[0])
    if (typeof parsed.title === "string" && typeof parsed.summary === "string") {
      return { title: parsed.title.trim(), summary: parsed.summary.trim() }
    }
  } catch {
    // Malformed JSON from model — silently skip
  }

  return null
}

// Returns null when the active model is cloud — UI will show "✦ nomear" button (RFC-0003).
export async function enrichKnowledgeRecord(
  record: KnowledgeRecord,
  modelData: LLM
): Promise<{ title: string; summary: string } | null> {
  if (!isLocalModel(modelData)) return null
  return callEnrichment(record.payload.content, modelData)
}

// Fire-and-forget: enriches all records produced by a local model.
// Title is updated only when it was a placeholder (non-markdown/html derive from content).
// Summary is always updated — deterministic title derivation does not skip LLM enrichment.
export function triggerEnrichment(
  records: KnowledgeRecord[],
  modelData: LLM,
  setKnowledge: Dispatch<SetStateAction<KnowledgeRecord[]>>
): void {
  if (!isLocalModel(modelData)) return

  for (const record of records) {
    enrichKnowledgeRecord(record, modelData)
      .then(async result => {
        if (!result) return
        const update: Partial<KnowledgeRecord> = { summary: result.summary }
        // Only override title when it was a placeholder — preserve deterministic titles
        // (e.g. markdown H1 headings, HTML <title> tags)
        if (PLACEHOLDER_TITLE_RE.test(record.title)) {
          update.title = result.title
        }
        await updateKnowledgeRecord(record.id, update)
        setKnowledge(prev =>
          prev.map(k => (k.id === record.id ? { ...k, ...update } : k))
        )
      })
      .catch(() => {
        // Enrichment is best-effort — failure is silent
      })
  }
}
