/*
 * Copyright (c) 2026 Danilo Borges (https://github.com/daniloborges)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 */

import { KnowledgeRecord } from "@/types/knowledge"
import { LLM } from "@/types"
import { updateKnowledgeRecord } from "@/lib/local-db/knowledge"
import { Dispatch, SetStateAction } from "react"

import { runHeadlessAgent } from "@/lib/runtime/headless-runner"

// Placeholder titles are generated by extract.ts for non-markdown/html content.
// Pattern: "typescript · 10:42" — if the title matches this, LLM may override it.
const PLACEHOLDER_TITLE_RE = /^.+ · \d{2}:\d{2}$/

// Local models: provider === "local" (auto-discovered via RFC-0001 discovery route)
// OR any model with an explicit baseUrl (manually configured custom models).
// Cloud models without baseUrl are not auto-enriched in v0 — RFC-0003 will add a "✦ nomear" button.
function isLocalModel(modelData: LLM): boolean {
  return modelData.provider === "local" || !!modelData.baseUrl
}

// Returns null when the active model is cloud — UI will show "✦ nomear" button (RFC-0003).
export async function enrichKnowledgeRecord(
  record: KnowledgeRecord,
  modelData: LLM
): Promise<{ title: string; summary: string } | null> {
  if (!isLocalModel(modelData)) return null

  try {
    const result = await runHeadlessAgent(
      record.payload.content,
      modelData,
      "/agents/background.agent",
      "run_enrichment",
      'Respond ONLY as JSON: { "intent_name": "save_metadata", "title": "...", "summary": "..." }'
    )
    if (result && result.title && result.summary) {
      return { title: result.title, summary: result.summary }
    }
  } catch (err) {
    console.error("Headless agent failed during manual enrichment:", err)
  }
  return null
}

export function triggerEnrichment(
  records: KnowledgeRecord[],
  modelData: LLM,
  setKnowledge: Dispatch<SetStateAction<KnowledgeRecord[]>>,
  setBackgroundQueue?: Dispatch<SetStateAction<any[]>>
): void {
  if (!isLocalModel(modelData)) return

  if (setBackgroundQueue) {
    const tasks = records.map(record => ({
      id: crypto.randomUUID(),
      type: "enrich_knowledge",
      payload: { record, modelData }
    }))
    setBackgroundQueue(prev => [...prev, ...tasks])
  }
}
